lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include('tasks.urls'))

]

tasks/urls.py
from django.urls import path
from . import views
app_name='task'
urlpatterns=[
path("",views.index,name='index'),
path("add/",views.add,name='add')
]

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
class NewTaskForm(forms.Form):
    task=forms.CharField(label='New Task')
def index(request):
    if 'tasks' not in request.session:
        request.session['tasks']=[]
    return render(request,'tasks/index.html',{
    'ta':request.session['tasks']

    })

def add(request):
    if request.method =="POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            task=form.cleaned_data['task']
            request.session['tasks'] +=[task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
                return render(request,'tasks/add.html',{
                'form':form
                })
    return render(request,'tasks/add.html',{
    'form':NewTaskForm()
    })

tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body%}
<h1>Tasks</h1>
	
	<form action='{% url "task:add"%}' method='post'>
		{% csrf_token %}
		{{form}}
		<input type='submit'>
	</form>
<a href='{% url "task:index" %}'>View tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body%}
<h1>tasks</h1>

<ul>
{% for t in ta %}
	<li>{{t}}</li>
{% empty %}
	<li>No Tasks</li>
{% endfor %}
</ul>
<a href='{% url "task:add" %}'>add a new task</a>

{% endblock %}

tasks/templates/tasks/layout.html
<!doctype html>

<html>
<head>
<title>
Tasks
</title>

</head>

<body>
{% block body %}
{% endblock %}

</body>
</html>